import random

from locust import HttpUser, between, task


class FeedbackUser(HttpUser):
    # Simulate users arriving between 0.1 and 0.5 seconds apart
    # This easily generates >100 requests/minute
    wait_time = between(0.1, 0.5)

    @task
    def send_feedback(self):
        scenarios = [
            "The billing page is broken.",
            "I love this app!",
            "Login failed with red error ... said 500.",
            "This is a massive security breach! Lawsuit incoming!",
            "The billing page is broken! I need a refund immediately!",  # Urgent
            "System crashed when I clicked logout. Error 503.",  # Technical
            "<script>alert('hack')</script> just testing",  # Security Attack
            "Your service is terrible, I am suing you.",  # Legal Threat
            "How do I reset my password?",  # General Support
            "Your app charged me $500 by mistake! Refund me now or I'm filing a lawsuit!",
            "I absolutely love how often your app crashes. It's the highlight of my day.",
            "The login button is broken on iOS 17.",
            "DROP TABLE users; --",
            "My account was hacked and I see strange transactions.",
            "Can you add a feature to export to PDF?",
            "El sistema no funciona, ayuda por favor.",
            "Billing is fine but the UX is confusing.",
            "I tried to call support for 3 hours. Unacceptable.",
            "Great update, fixed the lagging issue.",
            "Is this compliant with GDPR article 17?",
            "My credit card was double charged.",
            "The api documentation is outdated.",
            "Blue screen of death when opening the settings menu.",
            "I want to speak to a manager immediately.",
            "Why is there a hidden fee on my invoice?",
            "asdf jkl; 1234 %%$#@",
            "The 2FA code never arrives.",
            "Your security certificate is expired.",
            "I am cancelling my subscription because of the price hike.",
            "Can I pay with Bitcoin?",
            "The dark mode contrast is too low for accessibility.",
            "I found a vulnerability in your checkout flow.",
            "Please delete all my data.",
            "Shipping was delayed by 2 weeks.",
            "The mobile app drains my battery in 10 minutes.",
            "Who is the CEO of this company?",
            "Error 404 on the landing page.",
            "I suspect a phishing attempt from your domain.",
            "Refund processed but money not received.",
            "The search functionality returns zero results.",
            "Nice UI but the backend is slow.",
            "I will report you to the Better Business Bureau.",
            "System is down.",
            "Is there a student discount?",
            "My profile picture disappeared.",
            "Authentication failed: invalid token.",
            "I love the new dashboard widgets!",
            "Stop sending me marketing emails.",
            "The font size is too small.",
            "How do I change my billing address?",
            "The application freezes on startup.",
            "Suspicious activity detected on my dashboard.",
            "Do you offer enterprise plans?",
            "The connection times out after 30 seconds.",
            "I forgot my username.",
            "The export to CSV feature is broken.",
            "Your AI chat bot is unhelpful.",
            "I received the wrong item.",
            "Is there a bug bounty program?",
            "The new navigation bar is intuitive.",
            "I cannot reset my password.",
            "There is a typo on the homepage.",
            "My data was leaked on the dark web.",
            "The integration with Slack is not working.",
            "I am very happy with the customer service.",
            "The app requires too many permissions.",
            "Why is the server in maintenance mode?",
            "I cannot upload files larger than 5MB.",
            "The invite link is invalid.",
            "This is the worst software I have ever used.",
            "Can you support French language?",
            "I need a receipt for last month.",
            "The graph is not rendering correctly.",
            "I am getting a 500 Internal Server Error.",
            "Your privacy policy is vague.",
            "I love the speed of the new update.",
            "My saved work was lost.",
            "How do I delete my account?",
            "The API rate limit is too low.",
            "I suspect unauthorized access.",
            "The color scheme causes eye strain.",
            "Can I have a demo?",
            "The documentation link is broken.",
            "I am unable to login via Google.",
            "The app crashes when I rotate the screen.",
            "Great job on the security features.",
            "I need help configuring the webhook.",
            "The pricing page is misleading.",
            "I cannot access the admin panel.",
            "The notifications are spammy.",
            "I want to upgrade my plan.",
            "The footer links are not working.",
            "I am experiencing high latency.",
            "The search filters are buggy.",
            "My payment was declined.",
            "I received a duplicate email.",
            "The video player is broken.",
            "I cannot download the invoice.",
            "The app is not compatible with Windows 11.",
            "I found a bug in the reporting tool.",
            "The loading spinner never stops.",
            "I want to partner with your company.",
            "The text overlaps on mobile screens.",
            "I cannot find the logout button.",
            "The verification email went to spam.",
            "I am satisfied with the resolution.",
            "The app is using too much memory.",
            "I need technical support ASAP.",
        ]

        # Add random number to bypass deduplication for the stress test
        text = f"{random.choice(scenarios)} [ReqID: {random.randint(1, 100000)}]"

        self.client.post("/feedback", json={"raw_content": text})
